---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-claim-incluster
  namespace: default
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
