name: Kubediff End to End Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-e2e:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s-version: ['1.24.2']

    steps:
    - uses: actions/checkout@v3.0.2

    - name: Install K8S ${{ matrix.k8s-version }}
      uses: helm/kind-action@v1.3.0
      with:
        version: v0.14.0
        cluster_name: kind
        config: ./config/config.yaml
        kubectl_version: v1.25.0
    - run: kubectl cluster-info
    - run: kubectl version
    - run: kubectl get pods -n kube-system
    - name: Create namespace
      run: kubectl create ns test-project-ci
