name: End to End Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-e2e:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s-version: ['v1.24.2']
        kubectl-version: ['v1.25.0']
        kind-version: ['v0.14.0']

    steps:
    - uses: actions/checkout@v3.0.2

    - name: Install K8S ${{ matrix.k8s-version }}
      uses: helm/kind-action@v1.3.0
      with:
        version: ${{ matrix.kind-version }}
        cluster_name: kind
        config: ./config/config.yaml
        kubectl_version: ${{ matrix.kubectl-version }}
        node_image: kindest/node:${{ matrix.k8s-version }}
    - run: kubectl cluster-info
    - run: kubectl version
    - run: kubectl get pods -n kube-system
    - name: Create namespace
      run: kubectl create ns test-project-ci
